### ISSUE TITLE
Refactor AJAX Row Layout

### ISSUE THREAD

**Issue by davidkpiano** [Glimpse/Glimpse.Client.Hud#121]
cc. @avanderhoorn 

Browser calls layout - requests to look like the history list in the client:
- We don’t need to worry about the https icon or the browser icon,
- the 1st like should look something like   `{url}                                              {time}`
- the 2nd line should look something like `{method} {statusIcon} {statusCode}      {size} {duration}`
- We should still keep the header that says “Size” and duration “Duration”

Browser calls transitions - items need to load from the top not the bottom
- The idea is for it to be the same as the request history list, hence loading from the top
- Note the animation/transition should make it obvious that a new item has loaded

Browser calls length - number of requests that we show shouldn’t be limited in the popup
- At the moment we limit the number of items we show to 4… this should be changed so that we show all
- Note the container the list is in should have a max height and a scrollbar should appear on overflow

**Comment by legomushroom** [comment]
> Browser calls transitions - items need to load from the top not the bottom

At the moment browser calls do load from top to bottom only for `expanded` view, for the `collapsed` view, the requests go from bottom to top which might be confusing.
