### ISSUE TITLE
[HUD]: add ellipsis at the end

### ISSUE THREAD

**Issue by legomushroom** [Glimpse/Glimpse.Client.Hud#143]
When the request `URL` is truncated we need to add ellipsis at the end:

![image](https://user-images.githubusercontent.com/1478800/27651985-b8f57998-5bff-11e7-8303-a5ca40d5ecae.png)

**Comment by legomushroom** [comment]
PR: https://github.com/Glimpse/Glimpse.Client.Hud/pull/148

**Comment by davidkpiano** [comment]
Verified:

<img width="238" alt="screen shot 2017-07-06 at 3 13 28 pm" src="https://user-images.githubusercontent.com/1093738/27928557-b4d54564-625d-11e7-9a63-ba3248f75e12.png">
