### ISSUE TITLE
[browser calls]: think about get rid of parts of the URL

### ISSUE THREAD

**Issue by legomushroom** [Glimpse/Glimpse.Client.Hud#149]
For the browser calls, we use `http://localhost:3000/` prefix:

![image](https://user-images.githubusercontent.com/1478800/27703336-a15c621a-5ccc-11e7-98d1-422ef4da092a.png)

We might benefit from removing the `http://localhost:3000/` as it reflects current apps URL.

**Comment by mike-kaufman** [comment]
RE behavior, we should be consistent with the client request list, which strips the schema/host/port when it is the same as client URL.  In this case, we would strip when the endpoint is the same as endpoint of the current browser nav.  

Reasoning: I'm trying to think of a reason we shouldn't do this.  The only thing I can think of is, if browser URL & glimpse client URL differ (e.g., `localhost` vs `127.0.0.1`) there will be inconsistencies in URL between HUD & client.  If our goal is to avoid this, we'd display full URLs in both client & HUD, and I think that's too much redundant/unnecessary info.

RE timing, not sure this is priority for M22.

**Comment by davidkpiano** [comment]
Verified in 0.22.8:

<img width="254" alt="screen shot 2017-07-12 at 10 35 02 am" src="https://user-images.githubusercontent.com/1093738/28122985-cdaebf68-66ed-11e7-97cb-af3527656872.png">
