### ISSUE TITLE
[Server calls section]: clarify server requests

### ISSUE THREAD

**Issue by legomushroom** [Glimpse/Glimpse.Client.Hud#152]
When I launch `Services` -> `httpbin.org Node Tests` -> `Http` I see bunch of browser calls but no `Server calls`.

![image](https://user-images.githubusercontent.com/1478800/27705996-7cb5a4f4-5cd5-11e7-9f5a-51dcb9d48753.png)

On ther Client I see a lot of `Web Services` calls to some outer endpoints:

![image](https://user-images.githubusercontent.com/1478800/27706108-e55f7aac-5cd5-11e7-8cf6-07c22b3533ca.png)

So I'm not usre if the behaviour is intended or this is a bug?

**Comment by mike-kaufman** [comment]
Closing, current behavior is expected.
