### ISSUE TITLE
[UI] AJAX calls have a strange horizontal line above data

### ISSUE THREAD

**Issue by philliphoff** [Glimpse/Glimpse.Client.Hud#158]
On all automated test requests, the HUD shows a strange horizontal line above the AJAX data:

<img width="782" alt="screen shot 2017-06-29 at 4 38 47 pm" src="https://user-images.githubusercontent.com/6402946/27715052-75f8ecfc-5ce9-11e7-8317-69346ed3759b.png">

The line disappears when expanding the HUD.

**Comment by davidkpiano** [comment]
This is not reproducible in any browser (although I did see it in the past - I believe it was fixed as a side-effect of another HUD fix)

**Comment by legomushroom** [comment]
@philliphoff please confirm if it is not relevant anymore.

**Comment by legomushroom** [comment]
Fixed here: https://github.com/Glimpse/Glimpse.Client.Hud/pull/165

**Comment by philliphoff** [comment]
The stray line is gone, but maybe needs some bottom padding (see clipped AJAX request).

![screen shot 2017-07-10 at 11 37 59 am](https://user-images.githubusercontent.com/6402946/28033842-5bc49eac-6564-11e7-99ed-611bab3503a2.png)

**Comment by davidkpiano** [comment]
@philliphoff Might be fixed in the next build.

**Comment by philliphoff** [comment]
The screenshot was with the latest bits from `release` branch of the repo.
