### ISSUE TITLE
HUD url doesn't correctly deep link to specified request

### ISSUE THREAD

**Issue by mike-kaufman** [Glimpse/Glimpse.Client.Hud#16]
**Repro:**
  1.  launch express.test.app
  2.  navigate to http://localhost:3000/
  3.  Click on HUD
 
 **Expected:**
request for `/` is selected in glimpse client

 **Actual:**
first request in request list is selected. 

It looks like the format of href target in HUD is incorect.  If you edit href to be http://localhost:3000/glimpse/client/requests/78920ca0ea6611e696ea5f68a2e5052b, then it works correctly.

We need to determine if any of the current params in the current URI are still necessary.

**Comment by davidkpiano** [comment]
Issue moved to [Glimpse/Glimpse.Node #770](https://github.com/Glimpse/Glimpse.Node/issues/770) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nikmd23** [comment]
This is now available in Glimpse for Node 0.18.9. Please see our [announcement issue](https://github.com/Glimpse/Home/issues/93) for more information.
