### ISSUE TITLE
[logs] No browser log counts captured for many logging tests

### ISSUE THREAD

**Issue by davidkpiano** [Glimpse/Glimpse.Client.Hud#190]
See below. It seems that for anything besides "Basic Console Logging statements" the log counts are being reported as 0, which is inaccurate.

<img width="623" alt="screen shot 2017-08-10 at 4 43 59 pm" src="https://user-images.githubusercontent.com/1093738/29191273-2be530f8-7deb-11e7-90c5-18ca5e3bdd38.png">

**Comment by avanderhoorn** [comment]
This is not an issue... `console.info()` is an info, `console.log()` is a log and hence why the count isn't changing for normal logs.
