### ISSUE TITLE
[Visual] Some visual tweak 

### ISSUE THREAD

**Issue by chetsangnil** [Glimpse/Glimpse.Client.Hud#24]
@davidkpiano I've just saw HUD on Node repo and it would be great if you could help me make these minor changes. 

![image](https://cloud.githubusercontent.com/assets/7482923/23381251/a261a952-fcf2-11e6-95af-5ff850f64068.png)

![image](https://cloud.githubusercontent.com/assets/7482923/23381255/a6821bde-fcf2-11e6-9e71-526e48517b8c.png)

![image](https://cloud.githubusercontent.com/assets/7482923/23381259/a9a3ede2-fcf2-11e6-815b-608c2c32739c.png)

![image](https://cloud.githubusercontent.com/assets/7482923/23381263/aea99e18-fcf2-11e6-9e08-8c9d8c052325.png)

**Comment by nikmd23** [comment]
This is now available in Glimpse for Node 0.18.9. Please see our [announcement issue](https://github.com/Glimpse/Home/issues/93) for more information.
