### ISSUE TITLE
labels are misaligned on windows

### ISSUE THREAD

**Issue by legomushroom** [Glimpse/Glimpse.Client.Hud#31]
There is few pixels difference in label vertical positions, screenshot from `Edge`:
![image](https://cloud.githubusercontent.com/assets/1478800/23969404/5b8d3f56-0994-11e7-80cc-cff6b628d8b3.png)

**Comment by avanderhoorn** [comment]
Note, this is a nice to have for M019

**Comment by avanderhoorn** [comment]
Talk to me and we will go over what needs to happen.

**Comment by davidkpiano** [comment]
Fixed by https://github.com/Glimpse/Glimpse.Client.Hud/pull/61 (once merged in)
