### ISSUE TITLE
clicking hud doesn't take user to to glimpse request for the current page in user's app

### ISSUE THREAD

**Issue by mike-kaufman** [Glimpse/Glimpse.Client.Hud#58]
**repro:**
 1.  launch express.test.app
 2.  navigate to http://localhost:3000/request/request-cookies. 
 3.  click on hud link

**expected:** 
glimpse opens on request for the navigation to /request/request-cookies 

**actual:**
glimpse opens on the top request in the request list.

**Comment by avanderhoorn** [comment]
Are you able to get more details on this? Does it just fail to find the request, does it not pass in the request id, is there a funky content type or status code?

**Comment by mike-kaufman** [comment]
> Are you able to get more details on this? Does it just fail to find the request, does it not pass in the request id, is there a funky content type or status code?

effectively, follow-mode is interfering such that when you click a specific request `A` that isn't at the top of the request list, you don't actually go to `A`, you go to whatever is at the top of the request list.

**Comment by avanderhoorn** [comment]
This has been addressed with the inclusion of the "is ajax header" for other ajax/fetch.
