### ISSUE TITLE
[Version] Add version check icon

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Client.Hud#85]
When client reports old version, hud should show icon.

**Comment by mike-kaufman** [comment]
I'm reactivating this.  The logic in place [here](https://github.com/Glimpse/Glimpse.Client/blob/dev/src/client/shell/update/UpdateActions.ts#L28-L35) means that if the user's current version is not in npm (e.g., we've deleted some old version for some reason), then they don't see an update icon.  

We should probably account for this.  E.g., if we have a show-stopper bug in version 0.20.1, we may choose to pull 0.20.1 from npm and push 0.20.2.  If 0.20.1 isn't in the response.time array, then toasts won't happen. 

I think we should do something like  `semver.lt(currentVersion, latestVersion)` here.  This addresses the issue in the comments where we don't want toasts in devtime.

**Comment by davidkpiano** [comment]
@mike-kaufman That seems like an unlikely scenario - can we envision a use-case where we would need to completely remove a version (instead of `deprecate` it), which is something that [NPM actively discourages](https://docs.npmjs.com/cli/unpublish)?

I agree that `semver.lt(currentVersion, latestVersion)` would be more robust but I don't think that precludes the current logic from going in this release.

**Comment by mike-kaufman** [comment]
The version check as coded is effectively useless if that version ever disappears from npm, for whatever reason.

I agree it is unlikely, however it is not impossible.  The downside here, is *if* we ever pull something from npm, then we're going to really want the version check to kick, as we had a good reason to pull it.  At that point, we should go from suggesting users update to being pretty forceful about it.

**Comment by avanderhoorn** [comment]
I coded the logic like this to account for versions being on our myget feed
but not on npm.

With the way npm is setup it's impossible delete a version. I think you can
unlist a version but it's still there. I really wanted to avoid adding a
lib that does semver version checking due to the size of the dependency
(then does I found we're fairly big). I'm happy to improve the logic in the
future but my thinking was that this is good enough for now and accounts
for our myget setup.

Mike, given my OOF I'll leave it up to you given this context.

**Comment by mike-kaufman** [comment]
OK, this is fine.  If it ever comes up, we can address it.
